name = "go-proxy-bingai"
main = "cloudflare/worker.js"
compatibility_date = "2024-04-29"
workers_dev = true
rules = [
  { type = "ESModule", globs = ["**/*.js"], fallthrough = true }
]

[placement]
mode = "smart"
